#version 430 core
#extension GL_GOOGLE_include_directive : require

#include "nvs.glsl"
layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (set = 1, r32f, binding = 1) uniform readonly image2D v_in[DIMS];
layout (set = 1, r32f, binding = 2) writeonly uniform image2D f_out;

float get_v(int coord, ivec2 idx)
{
	if (idx != clamp(idx, ivec2(0), imageSize(v_in[coord]) - ivec2(1)))
		return 0.f;

	return imageLoad(v_in[coord], idx).x;
}

float div_v(ivec2 p)
{
	float div = 0;

	const ivec2 stencil[DIMS] = {
		ivec2(1, 0),
		ivec2(0, 1)
	};

	for (int i = 0; i < DIMS; ++i) {
		ivec2 p1 = p;
		ivec2 p2 = p + stencil[i];

		div += get_v(i, p2) - get_v(i, p1);  
	}

	return div/(2*DELTA_X); 
}

void main()
{
    ivec2 idx = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(f_out);

	if (idx.x >= size.x || idx.y >= size.y)
		return;

	float f = RHO*div_v(idx)/TIMESTEP;

	imageStore(f_out, idx, vec4(f, 0, 0, 0));
}
