#version 430 core
#extension GL_GOOGLE_include_directive : require

#include "nvs2_flip.glsl"

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#define declare_sample(image)\
float sample_##image(int coord, vec2 p)\
{\
	p[(1 + coord) & 0x1] -= 0.5;\
\
	ivec2 size = imageSize(image[coord]);\
\
	ivec2 px0 = clamp(ivec2(floor(p)), ivec2(0), size - ivec2(1));\
	ivec2 px1 = clamp(px0, ivec2(0), size - ivec2(1));\
\
	float u = fract(p.x);\
	float v = fract(p.y);\
\
	float v00 = imageLoad(image[coord], ivec2(px0.x,px0.y)).x;\
	float v01 = imageLoad(image[coord], ivec2(px0.x,px1.y)).x;\
	float v10 = imageLoad(image[coord], ivec2(px1.x,px0.y)).x;\
	float v11 = imageLoad(image[coord], ivec2(px1.x,px1.y)).x;\
\
	float v0 = mix(v00, v10, u);\
	float v1 = mix(v01, v11, u);\
\
	return mix(v0, v1, v);\
}\
vec2 get_##image(vec2 p)\
{\
	float vx = sample_##image(0, p);\
	float vy = sample_##image(1, p);\
\
	return vec2(vx,vy);\
}\

declare_sample(v_pre_proj)
declare_sample(v_proj)

uint pcg_hash(uint v) {
    uint state = v * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float hash_to_float(uint h) {
    return float(h) * (1.0 / 4294967296.0);
}

vec2 RK4(vec2 x0, float dt)
{
	vec2 k1 = get_v_proj(x0);
	vec2 k2 = get_v_proj(x0 + 0.5*dt*k1);
	vec2 k3 = get_v_proj(x0 + 0.5*dt*k2);
	vec2 k4 = get_v_proj(x0 + dt*k3);

	return x0 + (1./6.) * dt * (k1 + 2.*k2 + 2.*k3 + k4);
}

void main()
{
	int idx = int(gl_GlobalInvocationID.x);

	if (idx > pc.count)
		return;

	ivec2 size = imageSize(bd_mask);

	int quo = idx/size.x;

	// Reset positions
	if (pc.step == 0) {
		uint h1 = pcg_hash(idx);
		uint h2 = pcg_hash(idx + 1);

		float f1 = hash_to_float(h1);
		float f2 = hash_to_float(h2); 

		float w = 50.f;

		vec2 c = vec2(size)/2;

		vec2 pos = w*(vec2(1.f) -2.f*vec2(f1,f2)) + c;

		u_part_pos[idx] = pos;

		vec2 r = normalize(pos - c);
		
		u_part_vel[idx] = vec2(r.y, -r.x);
		return;
	}

	vec2 p_old = u_part_pos[idx];

	vec2 correction = get_v_proj(p_old) - get_v_pre_proj(p_old); 

	vec2 k1 = u_part_vel[idx] + correction;
	vec2 k2 = get_v_proj(p_old + 0.5 * TIMESTEP * k1); 
	vec2 k3 = get_v_proj(p_old + TIMESTEP * k2); 

	vec2 p_new = p_old + TIMESTEP * (1./6.) * (k1 + 4*k2 + k3);

	// velocity to be deposited and corrected after the next pressure solve
	vec2 v_new = mix(k1, get_v_proj(p_new), GRID_WT);

	u_part_pos[idx] = p_new;
	u_part_vel[idx] = v_new;
}
