#version 430 core
#extension GL_GOOGLE_include_directive : require

#include "nvs2_flip.glsl"

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#define DAMP 0.6
#define G 2

#define declare_sample(image)\
float sample_##image(int coord, vec2 p)\
{\
	p[(1 + coord) & 0x1] -= 0.5;\
\
	ivec2 size = imageSize(image[coord]);\
\
	ivec2 px0 = clamp(ivec2(p), ivec2(0), size - ivec2(1));\
	ivec2 px1 = clamp(px0 + ivec2(1), ivec2(0), size - ivec2(1));\
\
	float u = fract(p.x);\
	float v = fract(p.y);\
\
	float v00 = imageLoad(image[coord], ivec2(px0.x,px0.y)).x;\
	float v01 = imageLoad(image[coord], ivec2(px0.x,px1.y)).x;\
	float v10 = imageLoad(image[coord], ivec2(px1.x,px0.y)).x;\
	float v11 = imageLoad(image[coord], ivec2(px1.x,px1.y)).x;\
\
	float v0 = mix(v00, v10, u);\
	float v1 = mix(v01, v11, u);\
\
	return mix(v0, v1, v);\
}\
vec2 get_##image(vec2 p)\
{\
	float vx = sample_##image(0, p);\
	float vy = sample_##image(1, p);\
\
	return vec2(vx,vy);\
}\

declare_sample(v_pre_proj)
declare_sample(v_proj)

uint pcg_hash(uint v) {
    uint state = v * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float hash_to_float(uint h) {
    return float(h) * (1.0 / 4294967296.0);
}

vec2 cursor_jet(vec2 c)
{
	if (!bool(pc.cursor_flags))
		return vec2(0);

	vec2 size = vec2(imageSize(bd_mask));
	vec2 p1 = pc.cursor1 * size;
	vec2 p2 = pc.cursor2 * size;
	vec2 vel = p2 - p1;

	//vec2 d = c - p1;
	//return (-3*vec2(d.y, -d.x) - 10*d)/ (0.1f + dot(d,d));

	vec2 O = p2 - vel*0.25;

	float speed = length(vel);

	if (speed > size.x/4)
		return vec2(0);

	bool valid = speed > 1e-3; 

	float S = sqrt((valid ? 8*speed : 1.f));
	vec2 V = valid ? normalize(vel) : vec2(0);
	vec2 X = vec2(V.y, -V.x);

	mat2 frame = valid ? mat2(V/(2*S),2*X/S) : mat2(1/S);
	vec2 r = (c - O)*frame;

	return S * V * exp(-dot(r,r)/10);
}

vec2 bounce(vec2 p1, vec2 p2, vec2 v, float R)
{
	return vec2(0);
}

void main()
{
	int idx = int(gl_GlobalInvocationID.x);

	if (idx > pc.count)
		return;

	ivec2 size = imageSize(bd_mask);

	int quo = idx/size.x;

	uint h1 = pcg_hash(idx);
	uint h2 = pcg_hash(idx + 1);

	float r1 = hash_to_float(h1);
	float r2 = hash_to_float(h2); 

	// Reset positions
	if (pc.step == 0) {

		vec2 c = vec2(size)/2;
		vec2 w = vec2(size)/4;

		vec2 pos = w*(vec2(1.f) -2.f*vec2(r1,r2)) + c - vec2(0.5);

		u_part_pos[idx] = pos;

		vec2 r = length(pos - c) > 1e-3 ? normalize(pos - c) : vec2(0);
		
		u_part_vel[idx] = -1*vec2(r.x, r.y);
		return;
	}

	vec2 p_old = u_part_pos[idx];
	vec2 v_grid = get_v_proj(p_old);

	vec2 correction = v_grid - get_v_pre_proj(p_old); 

	vec2 k1 = u_part_vel[idx] + correction;
	vec2 k2 = get_v_proj(p_old - 0.5 * TIMESTEP * k1); 
	vec2 k3 = get_v_proj(p_old - TIMESTEP * k2); 

	vec2 p_new = p_old + TIMESTEP * (1./6.) * (k1 + 4*k2 + k3);
	vec2 v_new = mix(k1, v_grid, 0.1);

	//p_new += 0.01*normalize(vec2(1.f) - 2.f*vec2(r1, r2));

	float S = length(v_new);
	float R = max(S*TIMESTEP, 0.9f);

	vec2 p_clamped = clamp(p_new, vec2(R), vec2(size) - vec2(R));

	if (p_new.x != p_clamped.x) {
		v_new.x = -DAMP*v_new.x;
	}

	if (abs(p_new.y - p_clamped.y) > 1e-3) {
		v_new.y = -DAMP*v_new.y;
	} else {
		v_new.y += -G*TIMESTEP;
	}

	p_new = p_clamped;

	v_new += cursor_jet(p_new);

	u_part_pos[idx] = p_new;
	u_part_vel[idx] = 0.995*v_new;
}
