#version 430 core
#extension GL_GOOGLE_include_directive : require

#include "nvs.glsl"

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#define DIMS 2

layout (set = 1, binding = 0, std430 ) buffer Particles
{
	FluidParticle u_parts[];
};
layout (set = 1, r32f, binding = 1) readonly uniform image2D v_in[DIMS];

layout (push_constant) uniform PC
{
	uint count;
	uint step;
} pc;

float sample_v(int coord, vec2 p)
{
	ivec2 size = imageSize(v_in[coord]); 

	p[(1 + coord) & 0x1] -= 0.5;

	float s = p.x;
	float t = p.y;

	int i0 = int(floor(s));
	int j0 = int(floor(t));

	int i1 = i0 + 1;
	int j1 = j0 + 1;

	i0 = clamp(i0, 0, size.x - 1);
	i1 = clamp(i1, 0, size.x - 1);

	j0 = clamp(j0, 0, size.y - 1);
	j1 = clamp(j1, 0, size.y - 1);

	float v00 = imageLoad(v_in[coord], ivec2(i0,j0)).x;
	float v01 = imageLoad(v_in[coord], ivec2(i0,j1)).x;
	float v10 = imageLoad(v_in[coord], ivec2(i1,j0)).x;
	float v11 = imageLoad(v_in[coord], ivec2(i1,j1)).x;

	float u = fract(s);
	float v = fract(t);

	float v0 = mix(v00, v10, u);
	float v1 = mix(v01, v11, u);

	return mix(v0, v1, v);
}
vec2 get_v(vec2 p)
{
	float vx = sample_v(0, p);
	float vy = sample_v(1, p);

	return vec2(vx,vy);
}

vec2 RK4(vec2 x0, float dt)
{
	vec2 k1 = get_v(x0);
	vec2 k2 = get_v(x0 + 0.5*dt*k1);
	vec2 k3 = get_v(x0 + 0.5*dt*k2);
	vec2 k4 = get_v(x0 + dt*k3);

	return x0 + (1./6.) * dt * (k1 + 2.*k2 + 2.*k3 + k4);
}

uint pcg_hash(uint v) {
    uint state = v * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float hash_to_float(uint h) {
    return float(h) * (1.0 / 4294967296.0);
}

void main()
{
	int idx = int(gl_GlobalInvocationID.x);

	if (idx > pc.count)
		return;

	ivec2 size = imageSize(bd_mask);

	int quo = idx/size.x;

	// Reset positions
	if (pc.step == 0) {
		uint h1 = pcg_hash(idx);
		uint h2 = pcg_hash(idx + 1);

		float f1 = hash_to_float(h1);
		float f2 = hash_to_float(h2); 

		u_parts[idx].pos = 100*(1.f - 2.f*vec2(f1,f2)) + 0.5*vec2(size);
		u_parts[idx].vel = vec2(0);
		return;
	}

	vec2 p_old = u_parts[idx].pos;
	vec2 p_new = RK4(p_old, TIMESTEP);

	u_parts[idx].pos = p_new;
	u_parts[idx].vel = get_v(p_old);
}
