
#version 430 core
#extension GL_GOOGLE_include_directive : require

#include "nvs.glsl"

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (set = 1, r32f, binding = 1) uniform image2D v_out[DIMS];
layout (set = 1, r32f, binding = 2) uniform readonly image2D p_in;
layout (set = 1, r32f, binding = 3) uniform readonly image2D lap_p_in;

float get_p(ivec2 idx, out float wt)
{
	if (any(lessThan(idx, vec2(0))) || 
		any(greaterThanEqual(idx, imageSize(bd_mask)))) {
		wt = 0.f;
		return 0.f;
	}

	wt = imageLoad(bd_mask, idx).x;
	return imageLoad(p_in, idx).x;
}

void main()
{
    ivec2 idx = ivec2(gl_GlobalInvocationID.xy);

	ivec2 stencil[DIMS] = {
		ivec2(-1, 0),
		ivec2(0, -1),
	};

	float wt_c;
	float pc = get_p(idx, wt_c);

	for (int i = 0; i < DIMS; ++i) {
		if (any(greaterThanEqual(idx, imageSize(v_out[i]))))
			continue;

		float wt;
		float p = get_p(idx + stencil[i], wt); 
		wt = min(wt, wt_c);

		float v = imageLoad(v_out[i], idx).x;

		float dp = (pc - p)/(2*DELTA_X);
		float v_proj = wt * (v + TIMESTEP * -dp/RHO);

		imageStore(v_out[i], idx, vec4(v_proj));
	}
}

