
#version 430 core
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_atomic_float : require

#include "nvs.glsl"
#include "../core/common.glsl"

layout (local_size_x = 16, local_size_y = 1, local_size_z = 1) in;

#define DIMS 2

layout (set = 1, binding = 0, std430 ) buffer Particles
{
	FluidParticle u_parts[];
};
layout (set = 1, r32f, binding = 1) writeonly uniform image2D v_out[DIMS];

layout (push_constant) uniform PC {
	uint count;
} pc;

void main()
{
	int idx = int(gl_GlobalInvocationID.x);

	if (idx >= pc.count)
		return;
}
