#version 430 core

layout(constant_id = 0) const int MIP_COUNT = 8;
layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (set = 0, r8_snorm, binding = 0) uniform image2D levels[MIP_COUNT];

layout (push_constant) uniform pc {
	uint u_level;
};

void main()
{
	ivec2 size = imageSize(levels[u_level + 1]);
	ivec2 idx = ivec2(gl_GlobalInvocationID.xy);

	if (any(greaterThanEqual(idx, size)) || any(lessThan(idx, ivec2(0))))
		return;

	float samples[4] = {
		imageLoad(levels[u_level], 2*idx).r,
		imageLoad(levels[u_level], 2*idx + ivec2(1,0)).r,
		imageLoad(levels[u_level], 2*idx + ivec2(0,1)).r,
		imageLoad(levels[u_level], 2*idx + ivec2(1,1)).r,
	};

	float avg = 0;
	for (int i = 0; i < 4; ++i) {
		avg += samples[i]; 
	}

	imageStore(levels[u_level + 1], idx, vec4(avg / 4.f));
}
