#version 430 core
#extension GL_GOOGLE_include_directive : require

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(binding = 0) uniform ubo {
	vec2 cursor1;
	vec2 cursor2;
	uint flags;
};

layout(binding = 1) writeonly uniform image2D img;

float gaussian(vec2 x, vec2 c, float sigma)
{
	vec2 v = x - c;
	float r_sq = dot(v,v); 
	return sigma*exp(-sigma*sigma*r_sq);
}

void main()
{
    uvec3 id = gl_GlobalInvocationID;
	ivec2 size = imageSize(img);

	if (id.x >= size.x || id.y >= size.y)
		return;

	ivec2 src = ivec2(id.xy);

	if (bool(flags)) {
		float power = 0.1f;
		float sigma = 0.5f;

		vec2 pos = src + vec2(0.5);
		vec2 vel = (cursor1 - cursor2)*size;

		float f = power*gaussian(pos, cursor2*size, sigma);
		imageStore(img, src, vec4(f,0,0,0));
	}
}


