#version 460 core
#extension GL_GOOGLE_include_directive : require

#include "fluid/shader/nvs2_flip.glsl"

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#define declare_sample(image)\
float sample_##image(int coord, vec2 p)\
{\
	p[(1 + coord) & 0x1] -= 0.5;\
\
	ivec2 size = imageSize(image[coord]);\
\
	ivec2 px0 = clamp(ivec2(p), ivec2(0), size - ivec2(1));\
	ivec2 px1 = clamp(px0 + ivec2(1), ivec2(0), size - ivec2(1));\
\
	float u = fract(p.x);\
	float v = fract(p.y);\
\
	float v00 = imageLoad(image[coord], ivec2(px0.x,px0.y)).x;\
	float v01 = imageLoad(image[coord], ivec2(px0.x,px1.y)).x;\
	float v10 = imageLoad(image[coord], ivec2(px1.x,px0.y)).x;\
	float v11 = imageLoad(image[coord], ivec2(px1.x,px1.y)).x;\
\
	float v0 = mix(v00, v10, u);\
	float v1 = mix(v01, v11, u);\
\
	return mix(v0, v1, v);\
}\
vec2 get_##image(vec2 p)\
{\
	float vx = sample_##image(0, p);\
	float vy = sample_##image(1, p);\
\
	return vec2(vx,vy);\
}\

declare_sample(v_pre_proj)
declare_sample(v_proj)

uint pcg_hash(uint v) {
    uint state = v * 747796405u + 2891336453u;
    uint word = ((state >> ((state >> 28u) + 4u)) ^ state) * 277803737u;
    return (word >> 22u) ^ word;
}

float hash_to_float(uint h) {
    return float(h) * (1.0 / 4294967296.0);
}

vec2 world_to_grid(vec2 p)
{
	vec2 size = vec2(imageSize(solid_mask));

	return p * size.y;
}

vec2 cursor_jet(vec2 c)
{
	if (!bool(pc.cursor_flags))
		return vec2(0);

	vec2 p1 = world_to_grid(pc.cursor1);
	vec2 p2 = world_to_grid(pc.cursor2);
	vec2 vel = p2 - p1;
	float speed = length(vel);

	vec2 d = c - p1;
	float f = length(d)/15;
	return -3*((speed > 1e-3 ? 0.1*normalize(vel) : vec2(0)) + normalize(d)) * 1/(1 + f*f*f);;

	vec2 O = p2 - vel*0.25;

	bool valid = speed > 1e-3; 

	float S = sqrt((valid ? 8*speed : 1.f));
	vec2 V = valid ? normalize(vel) : vec2(0);
	vec2 X = vec2(V.y, -V.x);

	mat2 frame = valid ? mat2(V/(2*S),2*X/S) : mat2(1/S);
	vec2 r = (c - O)*frame;

	return S * V * exp(-dot(r,r)/10);
}

float solid_wt(vec2 p)
{
	vec2 size = vec2(imageSize(solid_mask));
	return texture(solid_mask_tex, p/size).r;
}

vec2 apply_solid_boundary(vec2 p1, vec2 p2, inout vec2 v, float R)
{
	ivec2 size = imageSize(solid_mask);

	p2 = clamp(p2, vec2(R), vec2(size) - vec2(R));

	float wc = solid_wt(p2);

	float h = 0.5;

	float wl = solid_wt(p2 + 0.5*vec2(-h,0));
	float wr = solid_wt(p2 + 0.5*vec2(h,0));
	float wb = solid_wt(p2 + 0.5*vec2(0,-h));
	float wt = solid_wt(p2 + 0.5*vec2(0,h));

	vec2 grad = vec2(wr - wl, wt - wb)/(2*h);
	float D = length(grad);

	if (D > 1e-4) {
		vec2 dir = -grad/D;
		vec2 proj = dir * min(dot(v,dir), 0.f);
		v -= proj;

		float d = (wc - 0.97)/D;
		p2 += -dir * max(0.f, R - d);
	}

	return p2;
}

void main()
{
	int idx = int(gl_GlobalInvocationID.x);

	if (idx > pc.count)
		return;

	ivec2 size = imageSize(solid_mask);

	int quo = idx/size.x;

	uint h1 = pcg_hash(pc.step + idx);
	uint h2 = pcg_hash(pc.step + idx + 1);

	float r1 = hash_to_float(h1);
	float r2 = hash_to_float(h2); 

	// Reset positions
	if (pc.step == 0) {

		vec2 c = vec2(size.x/2, size.y/2);
		vec2 w = vec2(size) * vec2(0.25, 0.25);

		vec2 pos = w*(vec2(1.f) -2.f*vec2(r1,r2)) + c - vec2(0.5);
		vec2 r = length(pos - c) > 1e-3 ? normalize(pos - c) : vec2(0);
		
		u_parts[idx] = FluidParticle(pos, vec2(0));
		return;
	}

	FluidParticle part = u_parts[idx];

	vec2 p_old = part.pos;
	vec2 v_grid = get_v_proj(p_old);

	vec2 correction = v_grid - get_v_pre_proj(p_old); 

	vec2 k1 = part.vel + correction;
	vec2 k2 = get_v_proj(p_old - 0.5 * TIMESTEP * k1); 
	vec2 k3 = get_v_proj(p_old - TIMESTEP * k2); 

	vec2 p_new = p_old + TIMESTEP * (1./6.) * (k1 + 4*k2 + k3);
	vec2 v_new = mix(k1, v_grid, GRID_WT);

	// The current trick for avoiding "clumping"
	p_new += 0.001*normalize(vec2(1.f) - 2.f*vec2(r1, r2));

	float S = length(v_new);
	float R = max(S*TIMESTEP, 0.5f);

	p_new = apply_solid_boundary(p_old, p_new, v_new, R);

	v_new.y += -G*TIMESTEP;
	v_new += cursor_jet(p_new);

	u_parts[idx] = FluidParticle(p_new, v_new);
}
