#version 460 core
#extension GL_GOOGLE_include_directive: require
#extension GL_KHR_shader_subgroup_basic: require
#extension GL_KHR_shader_subgroup_ballot: require

layout (local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

layout (set = 0, binding = 0) buffer Input
{
	uint s_data[];
};

layout(set = 0, binding = 1) buffer Output
{
	uint s_hist[];
};

layout (push_constant) uniform PC{
	uint u_count;
	uint u_shift;
};

uint get_key(uint idx)
{
	return s_data[idx];
}

void main()
{
	const uint idx = gl_GlobalInvocationID.x;
	const uint digits = gl_SubgroupSize;

	const bool inb = idx < u_count;

	uint key = inb ? get_key(idx) : 0u;

	uint bucket = (key >> u_shift) & ((1 << digits) - 1);
	uint this_bucket = gl_SubgroupInvocationID;

	uvec4 mask = subgroupBallot(inb && (this_bucket == bucket));
	uint count = subgroupBallotBitCount(mask);

	if (count > 0) {
		uint hist_offset = digits * gl_WorkGroupID.x + this_bucket;
		atomicAdd(s_hist[hist_offset], count);
	}
}
