#version 460 core
#extension GL_GOOGLE_include_directive: require
#extension GL_KHR_shader_subgroup_basic: require
#extension GL_KHR_shader_subgroup_ballot: require

#define DATA_TYPE uint

layout (local_size_x = 1024, local_size_y = 1, local_size_z = 1) in;

const uint NOT_READY = (0x0 << 30);
const uint AGGREGATE = (0x1 << 30);
const uint PREFIX = (0x2 << 30);
const uint STATUS_MASK = (0x3 << 30);
const uint VALUE_MASK = ~STATUS_MASK;

const uint BITS_PER_DIGIT = 6;
const uint DIGITS = (1 << BITS_PER_DIGIT);

layout (std430, set = 0, binding = 0) buffer TileInfo {
	uint s_next_tile;
	uint s_tile_info[];
};

layout (set = 0, binding = 1) buffer DigitOffsets {
	uint s_digit_offsets[];
};

layout (set = 0, binding = 2) readonly buffer Input
{
	DATA_TYPE s_input[];
};

layout (set = 0, binding = 3) writeonly buffer Output
{
	DATA_TYPE s_output[];
};

layout (push_constant) uniform PC {
	uint u_count;
	uint u_stage;
};

shared uint tile_id;
shared uint tile_counts[DIGITS];

uint get_digit(DATA_TYPE data, uint stage)
{
	uint key = data;
	return (key >> (u_stage * BITS_PER_DIGIT)) & (DIGITS - 1); 
}
void main()
{
	if (gl_LocalInvocationID.x == 0)
		tile_id = atomicAdd(s_next_tile, 1u);

	barrier();

	const uint idx = gl_GlobalInvocationID.x;

	DATA_TYPE data = s_input[idx];

	uint digit = get_digit(data, u_stage);

	// this will be set to 1 for each invocation whose digit matches
	// ours
	uvec4 mask = uvec4(0xFFFFFFFF);

	// reduce mask to only be one for invocations whose digit agrees
	// with our designated one
	for (int b = 0; b < BITS_PER_DIGIT; ++b) {
		bool is_set = bool((digit >> b) & 0x1);
		// one for all invocations whose digit has the this bit set
		uvec4 ballot = subgroupBallot(is_set); 
		mask &= is_set ? ballot : ~ballot;
	}

	uint my_count = subgroupBallotBitCount(mask);

	// only the first invocation with a particular digit writes to shared memory.
	//
	// subgroupBallotFindLSB is always defined because at the minimum, this 
	// invocation has this digit.
	const bool is_leader = gl_SubgroupInvocationID == subgroupBallotFindLSB(mask);

	if (is_leader) {
		atomicAdd(tile_counts[digit], my_count);
	}

	barrier();

	if (gl_LocalInvocationID.x < DIGITS) {
		uint my_digit = gl_LocalInvocationID.x;

		uint count = tile_counts[my_digit];
		uint info_slot = tile_id * DIGITS + my_digit;
		atomicExchange(s_tile_info[info_slot], AGGREGATE | (count & VALUE_MASK));

		uint excl_count = 0u;
		int look = int(tile_id) - 1;

		while (look >= 0) {
			uint info;
			do {
				info = atomicAdd(s_tile_info[look * DIGITS + my_digit], 0u);
			} while ((info & STATUS_MASK) == NOT_READY);

			excl_count += info & VALUE_MASK;

			if ((info & STATUS_MASK) == AGGREGATE) {
				--look;
			} else {
				break;
			}
		}

		uint incl_count = excl_count + count;
		atomicExchange(s_tile_info[info_slot], PREFIX | (incl_count));

		tile_counts[my_digit] = 0;
	}

	uint my_offset = subgroupBallotExclusiveBitCount(mask);

	for (int grp = 0; grp < gl_NumSubgroups; ++grp) {
		barrier();

		if (gl_SubgroupID == grp) {
			my_offset += tile_counts[digit];
			if (is_leader)
				tile_counts[digit] += my_count;
		}
	}

	uint out_idx = s_digit_offsets[u_stage * DIGITS + digit] + my_offset;

	s_output[out_idx] = data;
}
